# Generated by Django 2.0.4 on 2018-06-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0)),
                ('is_use', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phonetic_symbol_e', models.CharField(max_length=100, null=True)),
                ('phonetic_symbol_a', models.CharField(max_length=100, null=True)),
                ('pronunciation_e', models.CharField(max_length=1000, null=True)),
                ('pronunciation_a', models.CharField(max_length=1000, null=True)),
                ('meanings', models.CharField(max_length=1000)),
                ('example_sentence', models.CharField(max_length=1000, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Books')),
            ],
        ),
    ]
