# Generated by Django 2.0.4 on 2018-06-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, unique=True)),
                ('phonetic_symbol_e', models.CharField(max_length=100, null=True)),
                ('phonetic_symbol_a', models.CharField(max_length=100, null=True)),
                ('pronunciation_e', models.CharField(max_length=1000, null=True)),
                ('pronunciation_a', models.CharField(max_length=1000, null=True)),
                ('meanings', models.CharField(max_length=1000)),
                ('example_sentence', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecitedBookWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Words')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecitedDefinedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.UserDefinedWords')),
            ],
        ),
    ]
