# Generated by Django 2.0.4 on 2018-06-24 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_userbook_userdefinedwords_userrecitedbookwords_userreciteddefinedwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recite_words_day', models.IntegerField(default=20)),
                ('review_words_day', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
