# Generated by Django 2.0.4 on 2018-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_userwordsplan_examine_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
    ]
