# Generated by Django 2.0.4 on 2018-06-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_books_total_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='example_sentence',
        ),
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='meanings',
        ),
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='phonetic_symbol_a',
        ),
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='phonetic_symbol_e',
        ),
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='pronunciation_a',
        ),
        migrations.RemoveField(
            model_name='userdefinedwords',
            name='pronunciation_e',
        ),
        migrations.AlterField(
            model_name='userdefinedwords',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Words'),
        ),
    ]
